packages:
  - "packages/*"
  - "apps/desktop"
  - "apps/site"

nodeLinker: hoisted
publicHoistPattern:
  - "*electron*"
  - "*node-pty*"
  - "*@vscode*"

overrides:
  nanoid: 3.3.18
  node-gyp: ^12.2.0

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  koffi: true
  node-pty: true
  sharp: true
